import React from "react";
import Form from "../../forms/components/Form";
import Input from "../../forms/components/Input";

export default function CardForm({
	onSubmit,
	onReset,
	validateForm,
	title,
	errors,
	data,
	onInputChange,
}) {
	return (
		<Form
			onSubmit={onSubmit}
			onReset={onReset}
			validateForm={validateForm}
			title={title}
			styles={{ maxWidth: "800px" }}
		>
			<Input
				name="title"
				label="Title"
				type="text"
				error={errors.title}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="subtitle"
				label="Subtitle"
				type="text"
				error={errors.subtitle}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="description"
				label="Description"
				type="text"
				error={errors.description}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="phone"
				label="Phone"
				type="phone"
				error={errors.phone}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="email"
				label="Email"
				type="email"
				error={errors.email}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="webUrl"
				label="Web"
				type="text"
				error={errors.webUrl}
				onChange={onInputChange}
				data={data}
				required={false}
				sm={6}
			/>
			<Input
				name="imageUrl"
				label="Image url"
				type="text"
				error={errors.imageUrl}
				onChange={onInputChange}
				data={data}
				required={false}
				sm={6}
			/>
			<Input
				name="imageAlt"
				label="Image alt"
				type="text"
				error={errors.imageAlt}
				onChange={onInputChange}
				data={data}
				required={false}
				sm={6}
			/>
			<Input
				name="state"
				label="State"
				type="text"
				error={errors.state}
				onChange={onInputChange}
				data={data}
				required={false}
				sm={6}
			/>
			<Input
				name="country"
				label="Country"
				type="text"
				error={errors.country}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="city"
				label="City"
				type="text"
				error={errors.city}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="street"
				label="Street"
				type="text"
				error={errors.street}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="houseNumber"
				label="House number"
				type="text"
				error={errors.houseNumber}
				onChange={onInputChange}
				data={data}
				required={true}
				sm={6}
			/>
			<Input
				name="zip"
				label="Zip"
				type="text"
				error={errors.zip}
				onChange={onInputChange}
				data={data}
				required={false}
				sm={6}
			/>
		</Form>
	);
}
